remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
 - jekyll-feed
 - jekyll-include-cache
 - jekyll-paginate
 - jekyll-sitemap

# Site settings
# To be replaced with your own information
title: "Your Site's Title"
subtitle: "A short, descriptive subtitle."
description: "A description of your website."
url: "https://nasact.github.io" # the base hostname & protocol for your site
repository: nasact/nasact.github.io
# Add this section to your existing _config.yml file
collections:
  projects:
    output: true
    permalink: /:collection/:name/
